from dataclasses import dataclass


@dataclass(slots=True)
class Keys:
    A = "a"
    B = "b"
    C = "c"
    D = "d"
    E = "e"
    F = "f"
    G = "g"
    H = "h"
    I = "i"
    J = "j"
    K = "k"
    L = "l"
    M = "m"
    N = "n"
    O = "o"
    P = "p"
    Q = "q"
    R = "r"
    S = "s"
    T = "t"
    U = "u"
    V = "v"
    W = "w"
    X = "x"
    Y = "y"
    Z = "z"
    SPECIAL1 = b"\xc3\xa0".decode()
    SPECIAL2 = b"\x00".decode()
    LEFT = SPECIAL1 + "K"
    DOWN = SPECIAL1 + "P"
    RIGHT = SPECIAL1 + "M"
    UP = SPECIAL1 + "H"
    INSERT = SPECIAL1 + "R"
    HOME = SPECIAL1 + "G"
    DEL = SPECIAL1 + "S"
    END = SPECIAL1 + "O"
    PG_UP = SPECIAL1 + "I"
    PG_DOWN = SPECIAL1 + "Q"
    F1 = SPECIAL2 + ";"
    F2 = SPECIAL2 + "<"
    F3 = SPECIAL2 + "="
    F4 = SPECIAL2 + ">"
    F5 = SPECIAL2 + "?"
    F6 = SPECIAL2 + "@"
    F7 = SPECIAL2 + "A"
    F8 = SPECIAL2 + "B"
    F9 = SPECIAL2 + "C"
    F10 = SPECIAL2 + "D"
    # F11 doesn't get captured.
    F12 = SPECIAL1 + b"\xc2\x86".decode()
    ENTER = "\r"
